
pixelflow.home: /app/pixelflow

apiserver.url: "192.168.0.10.nip.io:8080"

infrastructure:
  type: kubernetes
  docker:
    workspace-root: "${pixelflow.home}/workspaces"
    network:
  kubernetes:
    workspace-root: "${pixelflow.home}/workspaces"

spring:
  liquibase:
    url: "jdbc:h2:file:${pixelflow.home}/database;DB_CLOSE_ON_EXIT=FALSE"
    user: sa
    password:
  r2dbc:
    url: "r2dbc:h2:file:///${pixelflow.home}/database"
    username: sa
    password: